### ISSUE TITLE
Retrieve organization's datasets when using organization_show

### ISSUE THREAD

**Issue by lauramoraes** [GSA/ckan-php-client#5]
Hello,

I am not sure if this is the correct way to suggest this. When making the request to organization_show endpoint (http://docs.ckan.org/en/latest/api/index.html#ckan.logic.action.get.organization_show) is it also possible to request the datasets from the organization if you send true in the parameter "include_datasets". This is really useful because it is the only way to access the private datasets of an organization.

I already created a forked version with this feature so I could use it, but it would be nice if everybody had access to this feature as well.

```php
/**
     * Returns organization with matching id or name
     *
     * @param string $id (id/name)
     *
     * @return mixed
     * @link http://docs.ckan.org/en/latest/api/index.html#ckan.logic.action.get.organization_show
     */
    public function organization_show($id, $include_datasets)
    {
        $solr_request = [
            'id' => $id,
            'include_datasets' => $include_datasets
        ];
        $data = json_encode($solr_request, JSON_PRETTY_PRINT);

        return $this->make_request(
            'POST',
            'action/organization_show',
            $data
        );
    }
```

**Comment by alex-perfilov-reisys** [comment]
for sure you can use any ckan allowed parameters. I did not include some of them only because we did not need it. You can make a Pull Request for this feature. But don't forget to set a default value for that param (False):
```
    public function organization_show($id, $include_datasets = False)
```
so existing code won't notice that change

**Comment by alex-perfilov-reisys** [comment]
solved by https://github.com/GSA/ckan-php-client/pull/6
